export * from './carreras.controller';
export * from './configuraciones.controller';
export * from './cronogramas.controller';
export * from './dignidades.controller';
export * from './jornadas.controller';
export * from './listas.controller';
export * from './cursos.controller';
export * from './actividades.controller';
export * from './paralelos.controller';
export * from './periodolectivos.controller';
export * from './resultados.controller';
export * from './roles.controller';
export * from './tipolistas.controller';
export * from './usuarios.controller';
export * from './usuariotipos.controller';
export * from './votos.controller'; 
export * from './estudiantes.controller'
