"use strict";
exports.__esModule = true;
exports.CatalogueStateEnum = exports.CatalogueTypeEnum = void 0;
var CatalogueTypeEnum;
(function (CatalogueTypeEnum) {
    CatalogueTypeEnum["ACADEMIC_PERIOD"] = "ACADEMIC_PERIOD";
    CatalogueTypeEnum["BLOOD_TYPE"] = "BLOOD_TYPE";
    CatalogueTypeEnum["CAREER_MODALITY"] = "CAREER_MODALITY";
    CatalogueTypeEnum["EDUCATION_LEVEL"] = "EDUCATION_LEVEL";
    CatalogueTypeEnum["ETHNIC_ORIGIN"] = "ETHNIC_ORIGIN";
    CatalogueTypeEnum["DISABILITY_TYPE"] = "DISABILITY_TYPE";
    CatalogueTypeEnum["IDENTIFICATION_TYPE"] = "IDENTIFICATION_TYPE";
    CatalogueTypeEnum["INSTITUTION_PRACTICES_TYPE"] = "INSTITUTION_PRACTICES_TYPE";
    CatalogueTypeEnum["GENDER"] = "GENDER";
    CatalogueTypeEnum["MARITAL_STATUS"] = "MARITAL_STATUS";
    CatalogueTypeEnum["PROJECT_SCOPE"] = "PROJECT_SCOPE";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_1"] = "SCHOLARSHIP_REASON_1";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_2"] = "SCHOLARSHIP_REASON_2";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_3"] = "SCHOLARSHIP_REASON_3";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_4"] = "SCHOLARSHIP_REASON_4";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_5"] = "SCHOLARSHIP_REASON_5";
    CatalogueTypeEnum["SCHOLARSHIP_REASON_6"] = "SCHOLARSHIP_REASON_6";
    CatalogueTypeEnum["SCHOLARSHIP_TYPE"] = "SCHOLARSHIP_TYPE";
    CatalogueTypeEnum["SCHOLARSHIP_FUNDING_TYPE"] = "SCHOLARSHIP_FUNDING_TYPE";
    CatalogueTypeEnum["STUDENT_OCCUPATION"] = "STUDENT_OCCUPATION";
    CatalogueTypeEnum["STUDENT_INCOME_FOR"] = "STUDENT_INCOME_FOR";
    CatalogueTypeEnum["REGISTRATION_TYPE"] = "REGISTRATION_TYPE";
    CatalogueTypeEnum["SCHOOL_TYPE"] = "SCHOOL_TYPE";
    CatalogueTypeEnum["SCHOOL_DAY"] = "SCHOOL_DAY";
    CatalogueTypeEnum["SEX"] = "SEX";
    CatalogueTypeEnum["YES_NO"] = "YES_NO";
    CatalogueTypeEnum["YES_NO_NA"] = "YES_NO_NA";
})(CatalogueTypeEnum = exports.CatalogueTypeEnum || (exports.CatalogueTypeEnum = {}));
var CatalogueStateEnum;
(function (CatalogueStateEnum) {
    CatalogueStateEnum["ACTIVE"] = "ACTIVE";
})(CatalogueStateEnum = exports.CatalogueStateEnum || (exports.CatalogueStateEnum = {}));
